<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\avalonia-logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\avalonia-logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\icons\**" />
	</ItemGroup>
  <ItemGroup>
    <None Update="App.axaml">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.0.0" />
		<PackageReference Include="Avalonia.Desktop" Version="12.0.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.0" />
		<PackageReference Include="DialogHost.Avalonia" Version="0.12.0" />
		<PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="11.4.12" />
		<PackageReference Include="ReactiveUI.SourceGenerators" Version="2.6.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ReactiveUI.SourceGenerators.Analyzers.CodeFixes" Version="2.6.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.1" />
		<PackageReference Include="Serilog" Version="4.3.1" />
		<PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Assets\icons\filled\" />
	  <Folder Include="Workspace\ModbusDemo\" />
	  <Folder Include="Workspace\Modbus\" />
	  <Folder Include="Workspace\OpcUa\" />
	  <Folder Include="Workspace\Startspace\" />
	  <Folder Include="Properties\" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="ModbusDemo.Controls.md" />
	  <None Update="route_map_signal_binding_roles.md" />
	  <None Update="Workspace\Modbus\ModbusView.axaml">
	    <SubType>Designer</SubType>
	  </None>
	  <None Update="Workspace\ModbusDemo\ModbusDemoView.axaml">
	    <SubType>Designer</SubType>
	  </None>
	  <None Update="Workspace\OpcUa\OpcUaView.axaml">
	    <SubType>Designer</SubType>
	  </None>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Configurator.Application\Configurator.Application.csproj" />
	</ItemGroup>
</Project>
